name: Check Jitsi-Box UI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'box-ui/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./box-ui

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
        cache-dependency-path: ./box-ui/package.json

    - run: npm install --legacy-peer-deps # Allow QR code scanner to be installed
    
    - run: npm run lint
        env:
          REACT_APP_MARSHA_URL: please_complete_this_@sampaccoud
